/**
 * One-time migration: imports leads from the existing Excel tracker into SQL Server.
 * Usage: npm run import-excel -- "path/to/file.xlsx"
 * Defaults to ../../resources/Syncaxis_leads_2026-09-05.xlsx if no path is given.
 *
 * Customers are deduplicated: rows sharing a Customer ID (or, if that's blank,
 * an exact company name match) are linked to the same Customers row instead of
 * creating a new customer per enquiry.
 */
import path from 'path';
import ExcelJS from 'exceljs';
import { getPool, sql } from '../src/db';

const CARD_COLLECTED_VALUES = new Set(['Yes', 'No', 'Photo Only', 'Not Recorded']);
const FOLLOW_UP_STATUS_VALUES = new Set([
  'Not Contacted', 'Contacted', 'Meeting Scheduled', 'Quotation Sent', 'Won', 'Lost', 'Not Relevant',
]);
const LEAD_TYPE_VALUES = new Set(['Project', 'Trading', 'Other']);

function cellText(cell: ExcelJS.Cell): string | null {
  const v = cell.value;
  if (v === null || v === undefined) return null;
  if (typeof v === 'object' && 'text' in (v as any)) return String((v as any).text).trim() || null;
  if (typeof v === 'object' && 'result' in (v as any)) return String((v as any).result).trim() || null;
  const s = String(v).trim();
  return s || null;
}

function cellDate(cell: ExcelJS.Cell): string | null {
  const v = cell.value;
  if (!v) return null;
  if (v instanceof Date) return v.toISOString().slice(0, 10);
  const s = cellText(cell);
  if (!s) return null;
  const d = new Date(s);
  return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10);
}

function normalizePriority(raw: string | null): string {
  if (!raw) return 'Warm';
  const s = raw.replace(/[^\w\s]/g, '').trim().toLowerCase();
  if (s.includes('hot')) return 'Hot';
  if (s.includes('cold')) return 'Cold';
  return 'Warm';
}

function normalizeEnum(raw: string | null, allowed: Set<string>, fallback: string): string {
  if (raw && allowed.has(raw)) return raw;
  return fallback;
}

interface ParsedFollowup {
  followUpDate: string;
  followUpBy: string | null;
  note: string | null;
}

// Notes Log format: "YYYY-MM-DD (Name): text | YYYY-MM-DD (Name): text | ..."
function parseNotesLog(raw: string | null): ParsedFollowup[] {
  if (!raw) return [];
  const entries = raw.split('|').map((s) => s.trim()).filter(Boolean);
  const results: ParsedFollowup[] = [];
  const re = /^(\d{4}-\d{2}-\d{2})\s*\(([^)]*)\)\s*:\s*(.*)$/s;
  for (const entry of entries) {
    const m = entry.match(re);
    if (m) {
      results.push({ followUpDate: m[1], followUpBy: m[2].trim() || null, note: m[3].trim() || null });
    } else {
      results.push({ followUpDate: new Date().toISOString().slice(0, 10), followUpBy: null, note: entry });
    }
  }
  return results;
}

async function main() {
  const filePath = process.argv[2]
    ? path.resolve(process.argv[2])
    : path.resolve(__dirname, '..', '..', 'resources', 'Syncaxis_leads_2026-09-05.xlsx');

  console.log('Reading workbook:', filePath);
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(filePath);
  const sheet = workbook.getWorksheet('Leads');
  if (!sheet) throw new Error('Could not find a "Leads" worksheet in the workbook');

  const headerRow = sheet.getRow(1);
  const headerMap = new Map<string, number>();
  headerRow.eachCell((cell, colNumber) => {
    const text = cellText(cell);
    if (text) headerMap.set(text, colNumber);
  });

  function col(name: string): number {
    const c = headerMap.get(name);
    if (!c) throw new Error(`Expected column "${name}" not found in worksheet header`);
    return c;
  }

  const columns = {
    enquiryNumber: col('Enquiry Number'),
    customerId: col('Customer ID'),
    country: col('Country'),
    state: col('State'),
    city: col('City'),
    applicationCategory: col('Application Category'),
    applicationDetail: col('Application (as recorded)'),
    productInterest: col('Product Interest'),
    companyName: col('Company Name'),
    department: col('Department'),
    contactPersonName: col('Contact Person Name'),
    email: col('Email ID'),
    phone: col('Phone No.'),
    cardCollected: col('Card Collected'),
    followUpStatus: col('Follow-Up Status'),
    priority: col('Priority'),
    inquirySource: col('Inquiry Source'),
    leadType: col('Lead Type'),
    movedToSourcePro: col('Moved to SourcePro'),
    leadValue: col('Lead Value'),
    leadGeneratedBy: col('Lead Generated By'),
    enquiryAssignedTo: col('Enquiry Assigned To'),
    nextFollowUpDate: col('Next Follow-up Date'),
    erpLeadNumber: col('ERP Lead Number'),
    orderNo: col('Order No'),
    orderDate: col('Order Date'),
    receivedDate: col('Received Date'),
    notes: col('Notes'),
    notesLog: col('Notes Log'),
  };

  const pool = await getPool();

  // Dedupe customers: key by Customer ID when present, else by a normalized
  // company name. Cache ids we've already inserted this run to avoid re-querying.
  const customerCache = new Map<string, number>();

  async function resolveCustomerId(row: ExcelJS.Row): Promise<number> {
    const customerCode = cellText(row.getCell(columns.customerId));
    const companyName = cellText(row.getCell(columns.companyName))!;
    const key = customerCode ? `code:${customerCode}` : `name:${companyName.toLowerCase()}`;

    const cached = customerCache.get(key);
    if (cached) return cached;

    if (customerCode) {
      const existing = await pool
        .request()
        .input('code', sql.NVarChar, customerCode)
        .query('SELECT Id FROM dbo.Customers WHERE CustomerCode = @code');
      if (existing.recordset.length) {
        customerCache.set(key, existing.recordset[0].Id);
        return existing.recordset[0].Id;
      }
    } else {
      const existing = await pool
        .request()
        .input('name', sql.NVarChar, companyName)
        .query('SELECT TOP 1 Id FROM dbo.Customers WHERE CompanyName = @name ORDER BY Id');
      if (existing.recordset.length) {
        customerCache.set(key, existing.recordset[0].Id);
        return existing.recordset[0].Id;
      }
    }

    const request = pool.request();
    request.input('customerCode', sql.NVarChar, customerCode);
    request.input('companyName', sql.NVarChar, companyName);
    request.input('department', sql.NVarChar, cellText(row.getCell(columns.department)));
    request.input('contactPersonName', sql.NVarChar, cellText(row.getCell(columns.contactPersonName)));
    request.input('email', sql.NVarChar, cellText(row.getCell(columns.email)));
    request.input('phone', sql.NVarChar, cellText(row.getCell(columns.phone)));
    request.input('country', sql.NVarChar, cellText(row.getCell(columns.country)));
    request.input('state', sql.NVarChar, cellText(row.getCell(columns.state)));
    request.input('city', sql.NVarChar, cellText(row.getCell(columns.city)));
    const result = await request.query(`
      INSERT INTO dbo.Customers (CustomerCode, CompanyName, Department, ContactPersonName, Email, Phone, Country, State, City)
      OUTPUT INSERTED.Id
      VALUES (@customerCode, @companyName, @department, @contactPersonName, @email, @phone, @country, @state, @city)
    `);
    const id = result.recordset[0].Id;
    customerCache.set(key, id);
    return id;
  }

  let customersCreated = 0;
  let leadsImported = 0;
  let skipped = 0;
  let followupsImported = 0;

  for (let rowNumber = 2; rowNumber <= sheet.rowCount; rowNumber++) {
    const row = sheet.getRow(rowNumber);
    const companyName = cellText(row.getCell(columns.companyName));
    if (!companyName) {
      skipped++;
      continue;
    }

    const cacheSizeBefore = customerCache.size;
    const customerId = await resolveCustomerId(row);
    if (customerCache.size > cacheSizeBefore) customersCreated++;

    const movedRaw = cellText(row.getCell(columns.movedToSourcePro));
    const leadValueRaw = row.getCell(columns.leadValue).value;
    const leadValue = typeof leadValueRaw === 'number' ? leadValueRaw : null;

    const request = pool.request();
    request.input('customerId', sql.Int, customerId);
    request.input('enquiryNumber', sql.NVarChar, cellText(row.getCell(columns.enquiryNumber)));
    request.input('applicationCategory', sql.NVarChar, cellText(row.getCell(columns.applicationCategory)));
    request.input('applicationDetail', sql.NVarChar, cellText(row.getCell(columns.applicationDetail)));
    request.input('productInterest', sql.NVarChar, cellText(row.getCell(columns.productInterest)));
    request.input('cardCollected', sql.NVarChar, normalizeEnum(cellText(row.getCell(columns.cardCollected)), CARD_COLLECTED_VALUES, 'Not Recorded'));
    request.input('followUpStatus', sql.NVarChar, normalizeEnum(cellText(row.getCell(columns.followUpStatus)), FOLLOW_UP_STATUS_VALUES, 'Not Contacted'));
    request.input('priority', sql.NVarChar, normalizePriority(cellText(row.getCell(columns.priority))));
    request.input('inquirySource', sql.NVarChar, cellText(row.getCell(columns.inquirySource)));
    request.input('leadType', sql.NVarChar, normalizeEnum(cellText(row.getCell(columns.leadType)), LEAD_TYPE_VALUES, 'Other'));
    request.input('movedToSourcePro', sql.Bit, movedRaw === 'Yes');
    request.input('leadValue', sql.Decimal(18, 2), leadValue);
    request.input('leadGeneratedBy', sql.NVarChar, cellText(row.getCell(columns.leadGeneratedBy)));
    request.input('enquiryAssignedTo', sql.NVarChar, cellText(row.getCell(columns.enquiryAssignedTo)));
    request.input('nextFollowUpDate', sql.Date, cellDate(row.getCell(columns.nextFollowUpDate)));
    request.input('erpLeadNumber', sql.NVarChar, cellText(row.getCell(columns.erpLeadNumber)));
    request.input('orderNo', sql.NVarChar, cellText(row.getCell(columns.orderNo)));
    request.input('orderDate', sql.Date, cellDate(row.getCell(columns.orderDate)));
    request.input('receivedDate', sql.Date, cellDate(row.getCell(columns.receivedDate)));
    request.input('notes', sql.NVarChar(sql.MAX), cellText(row.getCell(columns.notes)));

    const result = await request.query(`
      INSERT INTO dbo.Leads (
        CustomerId, EnquiryNumber, ApplicationCategory, ApplicationDetail, ProductInterest, CardCollected,
        FollowUpStatus, Priority, InquirySource, LeadType, MovedToSourcePro, LeadValue,
        LeadGeneratedBy, EnquiryAssignedTo, NextFollowUpDate, ErpLeadNumber, OrderNo, OrderDate, ReceivedDate, Notes
      )
      OUTPUT INSERTED.Id
      VALUES (
        @customerId, @enquiryNumber, @applicationCategory, @applicationDetail, @productInterest, @cardCollected,
        @followUpStatus, @priority, @inquirySource, @leadType, @movedToSourcePro, @leadValue,
        @leadGeneratedBy, @enquiryAssignedTo, @nextFollowUpDate, @erpLeadNumber, @orderNo, @orderDate, @receivedDate, @notes
      )
    `);
    const leadId = result.recordset[0].Id;
    leadsImported++;

    const notesLogRaw = cellText(row.getCell(columns.notesLog));
    const followups = parseNotesLog(notesLogRaw);
    for (const f of followups) {
      await pool
        .request()
        .input('leadId', sql.Int, leadId)
        .input('followUpDate', sql.Date, f.followUpDate)
        .input('followUpBy', sql.NVarChar, f.followUpBy)
        .input('note', sql.NVarChar(sql.MAX), f.note)
        .query('INSERT INTO dbo.Followups (LeadId, FollowUpDate, FollowUpBy, Note) VALUES (@leadId, @followUpDate, @followUpBy, @note)');
      followupsImported++;
    }
  }

  console.log(
    `Import complete. Customers created: ${customersCreated}, leads imported: ${leadsImported}, ` +
    `skipped rows (no company name): ${skipped}, follow-ups imported: ${followupsImported}`
  );
  process.exit(0);
}

main().catch((err) => {
  console.error('Import failed:', err);
  process.exit(1);
});
