import { useEffect, useState, useCallback } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { fetchLeads, fetchMeta, deleteLead } from '../api';
import type { Lead, MetaResponse } from '../types';
import { StatusBadge, ProductBadge } from '../components/StatusBadge';
import { ConfirmDialog } from '../components/ConfirmDialog';
import { AdminTabs } from '../components/AdminTabs';
import { PageSizeSelect } from '../components/PageSizeSelect';
import { HeaderFilterDropdown } from '../components/HeaderFilterDropdown';
import { formatInr, formatDate, sortProductInterests } from '../utils/format';

export function AdminLeadsPage() {
  const navigate = useNavigate();
  const [items, setItems] = useState<Lead[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [q, setQ] = useState('');
  const [status, setStatus] = useState('');
  const [productInterest, setProductInterest] = useState('');
  const [leadGeneratedBy, setLeadGeneratedBy] = useState('');
  const [sortBy, setSortBy] = useState('UpdatedAt');
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('desc');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [pendingDelete, setPendingDelete] = useState<Lead | null>(null);
  const [meta, setMeta] = useState<MetaResponse | null>(null);

  useEffect(() => {
    fetchMeta().then(setMeta).catch(() => {});
  }, []);

  const load = useCallback(() => {
    setLoading(true);
    setError(null);
    fetchLeads({ q, status, productInterest, leadGeneratedBy, sortBy, sortDir, page, pageSize })
      .then((res) => {
        setItems(res.items);
        setTotal(res.total);
      })
      .catch((err) => setError(err.message))
      .finally(() => setLoading(false));
  }, [q, status, productInterest, leadGeneratedBy, sortBy, sortDir, page, pageSize]);

  useEffect(() => {
    load();
  }, [load]);

  function handleSearchSubmit(e: React.FormEvent) {
    e.preventDefault();
    setPage(1);
    load();
  }

  async function confirmDelete() {
    if (!pendingDelete) return;
    try {
      await deleteLead(pendingDelete.id);
      setPendingDelete(null);
      load();
    } catch (err: any) {
      setError(err.message);
      setPendingDelete(null);
    }
  }

  function handleSort(column: string) {
    if (sortBy === column) {
      setSortDir((d) => (d === 'asc' ? 'desc' : 'asc'));
    } else {
      setSortBy(column);
      setSortDir('asc');
    }
    setPage(1);
  }

  // Called as a plain function (not JSX) so it isn't treated as its own
  // component - defining it as <SortableHeader/> would give React a new
  // component identity every render and remount the <th> each time.
  function sortableHeader(label: string, column: string, filter?: React.ReactElement) {
    const active = sortBy === column;
    return (
      <th key={column} className="sortable-header">
        <span onClick={() => handleSort(column)}>
          {label}
          <span className={`sort-indicator${active ? ' active' : ''}`}>{active ? (sortDir === 'asc' ? '▲' : '▼') : '⇅'}</span>
        </span>
        {filter && <span onClick={(e) => e.stopPropagation()}>{filter}</span>}
      </th>
    );
  }

  const totalPages = Math.max(1, Math.ceil(total / pageSize));

  return (
    <div className="page">
      <div className="page-header">
        <h1>Admin</h1>
      </div>

      <AdminTabs />

      <p className="hint-text admin-intro">
        Deleting here is permanent from this UI and can't be undone from the app.
      </p>

      <form className="filter-bar" onSubmit={handleSearchSubmit}>
        <input
          type="text"
          className="search-input"
          placeholder="Search company, contact, email, phone, enquiry #..."
          value={q}
          onChange={(e) => setQ(e.target.value)}
        />
        <button type="submit" className="btn">Search</button>
      </form>
      <p className="hint-text">Use the ⏷ icon on Status, Product Interest or Generated By column headers to filter by that column.</p>

      {error && <div className="alert alert-error">{error}</div>}

      <div className="table-wrap">
        <table>
          <thead>
            <tr>
              {sortableHeader('Enquiry No', 'EnquiryNumber')}
              {sortableHeader('Company Name', 'CompanyName')}
              {sortableHeader('Status', 'FollowUpStatus', (
                <HeaderFilterDropdown
                  options={meta?.followUpStatus || []}
                  value={status}
                  onChange={(v) => { setStatus(v); setPage(1); }}
                  allLabel="All statuses"
                  extraOption={{ value: 'OpenPipeline', label: 'Open Pipeline (Active)' }}
                />
              ))}
              {sortableHeader('Product Interest', 'ProductInterest', (
                <HeaderFilterDropdown
                  options={sortProductInterests(meta?.productInterests || [])}
                  value={productInterest}
                  onChange={(v) => { setProductInterest(v); setPage(1); }}
                  allLabel="All product interests"
                />
              ))}
              {sortableHeader('Application Detail', 'ApplicationDetail')}
              {sortableHeader('Lead Value', 'LeadValue')}
              {sortableHeader('Generated By', 'LeadGeneratedBy', (
                <HeaderFilterDropdown
                  options={meta?.generators || []}
                  value={leadGeneratedBy}
                  onChange={(v) => { setLeadGeneratedBy(v); setPage(1); }}
                  allLabel="All generated by"
                />
              ))}
              {sortableHeader('Created', 'CreatedAt')}
              <th></th>
            </tr>
          </thead>
          <tbody>
            {loading && (
              <tr><td colSpan={9} className="empty-state">Loading...</td></tr>
            )}
            {!loading && items.length === 0 && (
              <tr><td colSpan={9} className="empty-state">No leads found.</td></tr>
            )}
            {!loading && items.map((lead) => (
              <tr key={lead.id} className="clickable-row" onClick={() => navigate(`/leads/${lead.id}`)}>
                <td>{lead.enquiryNumber || '-'}</td>
                <td>
                  <div className="cell-primary">{lead.customer.companyName}</div>
                  {lead.customer.city && <div className="cell-secondary">{lead.customer.city}{lead.customer.state ? `, ${lead.customer.state}` : ''}</div>}
                </td>
                <td><StatusBadge status={lead.followUpStatus} /></td>
                <td><ProductBadge product={lead.productInterest} /></td>
                <td>{lead.applicationDetail || '-'}</td>
                <td>{lead.leadValue !== null ? formatInr(lead.leadValue) : '-'}</td>
                <td>{lead.leadGeneratedBy || '-'}</td>
                <td>{formatDate(lead.createdAt)}</td>
                <td className="row-actions" onClick={(e) => e.stopPropagation()}>
                  <Link to={`/leads/${lead.id}/edit`} className="btn-link">Edit</Link>
                  <button className="btn-link btn-danger-link" onClick={() => setPendingDelete(lead)}>Delete</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <div className="pagination">
        <PageSizeSelect value={pageSize} onChange={(size) => { setPageSize(size); setPage(1); }} />
        <div className="pagination-controls">
          <button className="btn" disabled={page <= 1} onClick={() => setPage((p) => p - 1)}>Previous</button>
          <span>Page {page} of {totalPages} ({total} leads)</span>
          <button className="btn" disabled={page >= totalPages} onClick={() => setPage((p) => p + 1)}>Next</button>
        </div>
      </div>

      {pendingDelete && (
        <ConfirmDialog
          title="Delete lead"
          message={`Delete the lead for "${pendingDelete.customer.companyName}" (Enquiry ${pendingDelete.enquiryNumber || '-'})? This cannot be undone from the UI.`}
          confirmLabel="Delete"
          onConfirm={confirmDelete}
          onCancel={() => setPendingDelete(null)}
        />
      )}
    </div>
  );
}
