import { useEffect, useState } from 'react';
import { fetchDashboardStats, fetchTeamTrend } from '../api';
import type { DashboardStats, TeamTrend, TeamTrendMetric, TrendPeriod } from '../api';
import { BreakdownBars } from '../components/BreakdownBars';
import { TeamTrendChart } from '../charts/TeamTrendChart';

const PERIOD_OPTIONS: { key: TrendPeriod; label: string }[] = [
  { key: 'weekly', label: 'Weekly' },
  { key: 'monthly', label: 'Monthly' },
  { key: 'quarterly', label: 'Quarterly' },
];

const METRIC_OPTIONS: { key: TeamTrendMetric; label: string }[] = [
  { key: 'enquiries', label: 'Enquiries Created' },
  { key: 'followups', label: 'Follow-ups Logged' },
  { key: 'orders', label: 'Sale Orders' },
];

export function TeamPerformancePage() {
  const [dash, setDash] = useState<DashboardStats | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [updatedAt, setUpdatedAt] = useState('');

  const [trendMetric, setTrendMetric] = useState<TeamTrendMetric>('enquiries');
  const [trendPeriod, setTrendPeriod] = useState<TrendPeriod>('monthly');
  const [trend, setTrend] = useState<TeamTrend | null>(null);
  const [trendError, setTrendError] = useState<string | null>(null);

  function load() {
    fetchDashboardStats()
      .then((d) => {
        setDash(d);
        setUpdatedAt(new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }));
      })
      .catch((err) => setError(err.message));
  }

  useEffect(() => {
    load();
  }, []);

  useEffect(() => {
    setTrendError(null);
    fetchTeamTrend(trendMetric, trendPeriod)
      .then(setTrend)
      .catch((err) => setTrendError(err.message));
  }, [trendMetric, trendPeriod]);

  return (
    <div className="page">
      <div className="page-header">
        <h1>Team Performance</h1>
        <div className="page-header-actions">
          {updatedAt && <span className="hint-text" style={{ margin: 0, alignSelf: 'center' }}>Updated {updatedAt}</span>}
          <button className="btn" onClick={load}>Refresh</button>
        </div>
      </div>

      {error && <div className="alert alert-error">{error}</div>}

      {dash && (
        <div className="dashboard-grid">
          <section className="detail-section">
            <h2>Leads Generated By</h2>
            <BreakdownBars items={dash.byGenerator.map((d) => ({ label: d.generator, value: d.count, to: `/leads?leadGeneratedBy=${encodeURIComponent(d.generator)}` }))} />
          </section>

          <section className="detail-section">
            <h2>Leads Assigned To</h2>
            <BreakdownBars items={dash.byAssignee.map((d) => ({ label: d.assignee, value: d.count, to: `/leads?assignedTo=${encodeURIComponent(d.assignee)}` }))} />
          </section>
        </div>
      )}

      <h2 className="dashboard-section-title">Performance Trend</h2>
      <div className="trend-chart-controls">
        <div className="trend-period-toggle">
          {METRIC_OPTIONS.map((opt) => (
            <button
              key={opt.key}
              type="button"
              className={`trend-period-btn${trendMetric === opt.key ? ' active' : ''}`}
              onClick={() => setTrendMetric(opt.key)}
            >
              {opt.label}
            </button>
          ))}
        </div>
        <div className="trend-period-toggle">
          {PERIOD_OPTIONS.map((opt) => (
            <button
              key={opt.key}
              type="button"
              className={`trend-period-btn${trendPeriod === opt.key ? ' active' : ''}`}
              onClick={() => setTrendPeriod(opt.key)}
            >
              {opt.label}
            </button>
          ))}
        </div>
      </div>

      {trendError && <div className="alert alert-error">{trendError}</div>}

      <section className="detail-section detail-section-wide">
        {trend && <TeamTrendChart data={trend} />}
      </section>
    </div>
  );
}
